name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore
        run: dotnet restore ReadySetRentables.Calculator.sln

      - name: Build
        run: dotnet build ReadySetRentables.Calculator.sln --no-restore --configuration Release

      - name: Test
        run: dotnet test ReadySetRentables.Calculator.sln --no-build --configuration Release

  deploy:
    # Only deploy on push to main (not PRs)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to UM790 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.UM790_HOST }}
          username: ${{ secrets.UM790_USER }}
          key: ${{ secrets.UM790_SSH_KEY }}
          port: ${{ secrets.UM790_SSH_PORT || 22 }}
          script: |
            cd ~/apps/ReadySetRentables
            ./deploy.sh
